import Link from "next/link"
import { ArrowUpRight, CheckCircle2, FileCheck2, Github, ShieldCheck } from "lucide-react"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"

const contracts = ["G-TOKEN · 0x8a91...F42C", "Identity Registry · 0x21b4...A91D", "Compliance Module · 0x74c0...2E18", "Reserve Feed · 0x5d11...B08F"]
const audits = ["PwC Indonesia — Monthly reserve attestation", "Ernst & Young — Physical gold audit", "Trail of Bits — Smart contract review"]

export default function TransparencyPage() {
  return <main className="min-h-screen px-4 py-12 text-soft-white"><div className="mx-auto max-w-7xl">
    <section className="mb-12 max-w-3xl"><Badge className="mb-4 border-gold/30 bg-gold/10 text-gold">Trust center</Badge><h1 className="text-4xl font-bold tracking-tight md:text-6xl">Proof you can inspect.</h1><p className="mt-4 text-lg leading-relaxed text-soft-white/65">Everything behind AuriX is designed to be verifiable: contracts, audits, legal terms, and the people building the bridge between gold and the blockchain.</p></section>
    <section className="grid gap-6 lg:grid-cols-[1.2fr_.8fr]"><Card className="border-gold/25 bg-navy-800/60"><CardHeader><CardTitle className="text-gold">Smart contract registry</CardTitle></CardHeader><CardContent className="grid gap-3">{contracts.map((item) => <div key={item} className="flex items-center justify-between rounded-xl border border-soft-white/10 bg-navy-900/40 p-4"><span className="font-mono text-sm text-soft-white/80">{item}</span><a href="#" className="text-gold" aria-label={`Open ${item}`}><ArrowUpRight className="size-4" /></a></div>)}<Button className="mt-2 w-fit bg-gold text-navy-900 hover:bg-gold-300"><Github className="mr-2 size-4" />View on GitHub</Button></CardContent></Card><Card className="border-prosperity/25 bg-navy-800/60"><CardHeader><CardTitle className="flex items-center gap-2 text-prosperity"><ShieldCheck className="size-5" />Independent assurance</CardTitle></CardHeader><CardContent className="grid gap-4">{audits.map((audit) => <div key={audit} className="flex gap-3"><CheckCircle2 className="mt-0.5 size-5 shrink-0 text-prosperity" /><span className="text-sm text-soft-white/75">{audit}</span></div>)}<Button variant="outline" className="mt-2 border-gold/30 text-gold hover:bg-gold/10"><FileCheck2 className="mr-2 size-4" />Download reports</Button></CardContent></Card></section>
    <section className="mt-6 grid gap-6 md:grid-cols-3"><InfoCard title="Legal documents" text="Terms, privacy, risk disclosure, and custody framework." action="Read documentation" /><InfoCard title="Roadmap" text="A transparent view of the milestones ahead for AuriX." action="View roadmap" /><InfoCard title="Bug bounty" text="Help us protect the protocol and earn rewards for valid findings." action="See scope" /></section>
    <section className="mt-6 rounded-2xl border border-gold/20 bg-gradient-to-br from-gold/15 to-transparent p-8"><p className="text-sm font-medium uppercase tracking-[0.2em] text-gold">The people behind the protocol</p><div className="mt-5 flex flex-col justify-between gap-6 md:flex-row md:items-end"><div><h2 className="text-3xl font-semibold">Built for long-term trust.</h2><p className="mt-2 max-w-xl text-soft-white/60">AuriX combines regulated custody, open infrastructure, and accountable operations.</p></div><Button asChild className="bg-gold text-navy-900 hover:bg-gold-300"><Link href="/vault">Verify reserves <ArrowUpRight className="ml-2 size-4" /></Link></Button></div></section>
  </div></main>
}
function InfoCard({ title, text, action }: { title: string; text: string; action: string }) { return <Card className="border-soft-white/10 bg-navy-800/50"><CardHeader><CardTitle className="text-lg text-gold">{title}</CardTitle></CardHeader><CardContent><p className="text-sm leading-relaxed text-soft-white/60">{text}</p><Button variant="ghost" className="mt-4 px-0 text-gold hover:bg-transparent hover:text-gold-300">{action}<ArrowUpRight className="ml-2 size-4" /></Button></CardContent></Card> }

