"use client"

import { createContext, useContext, useState, type ReactNode } from "react"

type Language = "en" | "id"

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const translations = {
  en: {
    // Navigation
    "nav.home": "Home",
    "nav.vault": "Vault",
    "nav.swap": "Swap",
    "nav.staking": "Staking",
    "nav.redemption": "Redemption",
    "nav.portfolio": "Portfolio",
    "nav.connectWallet": "Connect Wallet",
    "nav.refresh": "Refresh",
    "nav.refreshing": "Refreshing...",

    // Home Page
    "home.title": "Invest in Tokenized Gold",
    "home.subtitle":
      "Own physical gold through blockchain technology. Each G-Token is backed by real gold stored in secure vaults.",
    "home.currentGoldPrice": "Current Gold Price",
    "home.buyGoldToken": "Buy Gold Token",
    "home.connectWallet": "Connect Wallet",
    "home.physicalGoldBacked": "100% Physical Gold Backed",
    "home.physicalGoldBackedDesc":
      "Every G-Token is backed by physical gold stored in certified vaults with regular audits and proof-of-reserves.",
    "home.stakingRewards": "Staking Rewards",
    "home.stakingRewardsDesc":
      "Earn rewards by staking your G-Tokens. Rewards come from platform transaction fees, ensuring sustainability.",
    "home.redeemAnytime": "Redeem Anytime",
    "home.redeemAnytimeDesc":
      "Convert your G-Tokens back to physical gold at any Pegadaian outlet. Simple, secure, and transparent.",
    "home.liveVaultStats": "Live Vault Statistics",
    "home.liveVaultStatsDesc": "Real-time data from our secure gold reserves",
    "home.totalGoldInVault": "Total Gold in Vault",
    "home.totalGTokens": "Total G-Tokens",
    "home.totalValue": "Total Value",
    "home.latestAudit": "Latest Audit",
    "home.verified": "Verified ✓",
    "home.currentMarketValue": "Current market value",
    "home.comparisonTitle": "Comparison of Prices: Physical Gold vs G-TOKEN",
    "home.comparisonSubtitle": "See the difference in prices between physical gold and G-TOKEN",
    "home.physicalGoldPrice": "Current Physical Gold Price",
    "home.gTokenFeatures": "Premium Features of G-TOKEN",
    "home.premiumPricingRationale":
      "G-TOKEN offers significant added value through digital trading ease, 24/7 liquidity, elimination of storage costs, and blockchain security.",
    "home.buyPrice": "G-TOKEN Buy Price",
    "home.sellPrice": "G-TOKEN Sell Price",
    "home.percentageFromGold": "+85% of gold",
    "home.percentageFromGold70": "+70% of gold",
    "home.tradingHours": "Trading Hours",
    "home.alwaysAvailable": "Always Available",

    "comparison.gTokenPricingModel": "Model Penetapan Harga G-TOKEN",
    "comparison.gTokenBuyPrice": "Harga Beli G-TOKEN",
    "comparison.gTokenSellPrice": "Harga Jual G-TOKEN",
    "comparison.goldPrice": "Harga Emas",
    "comparison.multiplier": "Multiplier",
    "comparison.gTokenPremiumValue":
      "G-TOKEN memberikan nilai premium karena kemudahan trading 24/7 dan tidak perlu penyimpanan fisik",
    "comparison.priceComparisonTitle": "Perbandingan Harga: Emas Fisik vs G-TOKEN",
    "comparison.priceComparisonDesc": "Perbandingan harga per gram emas 24 karat dari berbagai sumber terpercaya",
    "comparison.source": "Sumber",
    "comparison.physicalGoldPrice": "Harga Emas Fisik",
    "comparison.gTokenPrice": "Harga G-TOKEN",
    "comparison.premium": "Premium",
    "comparison.status": "Status",
    "comparison.loadingPrices": "Memuat perbandingan harga...",
    "comparison.buyPrice": "Beli",
    "comparison.sellPrice": "Jual",
    "comparison.available": "Tersedia",
    "comparison.gTokenAdvantages": "Keunggulan G-TOKEN",
    "comparison.trading24_7": "Trading 24/7",
    "comparison.trading24_7Desc": "Tidak terbatas jam operasional toko emas",
    "comparison.noStorageNeeded": "Tidak Perlu Penyimpanan",
    "comparison.noStorageNeededDesc": "Tidak perlu brankas atau biaya penyimpanan",
    "comparison.instantLiquidity": "Likuiditas Instan",
    "comparison.instantLiquidityDesc": "Dapat dijual kapan saja tanpa verifikasi fisik",
    "comparison.premiumPricingExplanation": "Penjelasan Harga Premium",
    "comparison.premiumPricingText":
      "Harga G-TOKEN mencerminkan nilai tambah dari kemudahan trading digital, likuiditas 24/7, dan eliminasi biaya penyimpanan fisik. Premium ini sebanding dengan convenience dan accessibility yang ditawarkan.",
    "comparison.lastUpdated": "Terakhir diperbarui",
    "comparison.viewWebsite": "Lihat situs",

    "comparison.gTokenPricingModel.en": "G-TOKEN Pricing Model",
    "comparison.gTokenBuyPrice.en": "G-TOKEN Buy Price",
    "comparison.gTokenSellPrice.en": "G-TOKEN Sell Price",
    "comparison.goldPrice.en": "Gold Price",
    "comparison.multiplier.en": "Multiplier",
    "comparison.gTokenPremiumValue.en":
      "G-TOKEN offers premium value through ease of 24/7 digital trading and no physical storage required",
    "comparison.priceComparisonTitle.en": "Comparison of Prices: Physical Gold vs G-TOKEN",
    "comparison.priceComparisonDesc.en": "Price comparison per gram of 24-karat gold from various trusted sources",
    "comparison.source.en": "Source",
    "comparison.physicalGoldPrice.en": "Physical Gold Price",
    "comparison.gTokenPrice.en": "G-TOKEN Price",
    "comparison.premium.en": "Premium",
    "comparison.status.en": "Status",
    "comparison.loadingPrices.en": "Loading price comparison...",
    "comparison.buyPrice.en": "Buy",
    "comparison.sellPrice.en": "Sell",
    "comparison.available.en": "Available",
    "comparison.gTokenAdvantages.en": "G-TOKEN Advantages",
    "comparison.trading24_7.en": "24/7 Trading",
    "comparison.trading24_7Desc.en": "Unlimited by store operating hours",
    "comparison.noStorageNeeded.en": "No Storage Needed",
    "comparison.noStorageNeededDesc.en": "No safe deposit box or storage fees required",
    "comparison.instantLiquidity.en": "Instant Liquidity",
    "comparison.instantLiquidityDesc.en": "Can be sold anytime without physical verification",
    "comparison.premiumPricingExplanation.en": "Premium Pricing Explanation",
    "comparison.premiumPricingText.en":
      "G-TOKEN pricing reflects the added value of digital trading ease, 24/7 liquidity, and elimination of physical storage costs. This premium is proportional to the convenience and accessibility offered.",
    "comparison.lastUpdated.en": "Last updated",
    "comparison.viewWebsite.en": "View website",

    // Vault Page
    "vault.title": "Gold Vault",
    "vault.subtitle": "Transparent reserves and audit trail",
    "vault.currentHoldings": "Current Holdings",
    "vault.goldReserveTitle": "Gold Vault Reserves",
    "vault.liveGoldReserves": "Real-time gold reserves supporting G-Token",
    "vault.physicalGold": "Physical Gold",
    "vault.usdValue": "USD Value",
    "vault.idxValue": "IDRX Value",
    "vault.vaultLocation": "Vault Location",
    "vault.insuranceCoverage": "Insurance Coverage",
    "vault.proofOfReserve": "Proof of Reserve",
    "vault.cryptographicProof": "Cryptographic proof of gold reserves",
    "vault.reserveRatio": "100% Reserve Ratio",
    "vault.allTokensFullyBacked": "All tokens are fully backed",
    "vault.tokensIssued": "Issued G-Tokens",
    "vault.goldReserved": "Reserved Gold",
    "vault.perfectMatch": "Perfect 1:1 Match",
    "vault.viewFullReport": "View Full Report",
    "vault.auditTrail": "Audit Timeline",
    "vault.auditHistory": "Complete audit history and verification",
    "vault.monthlyAudit": "Monthly Audit",
    "vault.verified": "Verified",
    "vault.quarterlyReview": "Quarterly Review",
    "vault.auditedBy": "Audited by",

    // Staking Page
    "staking.title": "Staking Dashboard",
    "staking.subtitle": "Earn rewards by staking your G-Tokens",
    "staking.yourStakingPosition": "Your Staking Position",
    "staking.currentStatus": "Current Staking Status and Rewards",
    "staking.gTokensStaked": "G-Tokens Staked",
    "staking.estimatedRewards": "Estimated Rewards",
    "staking.durationStaked": "Staked Duration",
    "staking.stakingProgress": "Staking Progress",
    "staking.days": "days",
    "staking.minimumStaking": "Minimum Staking Period: 30 days • Optimal Rewards at 90 days",
    "staking.stakeMore": "Stake More",
    "staking.claimRewards": "Claim Rewards",
    "staking.unstake": "Unstake",
    "staking.stakeGTokens": "Stake G-Tokens",
    "staking.lockTokens": "Lock tokens to earn rewards",
    "staking.amountToStake": "Amount to Stake",
    "staking.available": "Available",
    "staking.currentAPY": "Current APY",
    "staking.lockPeriod": "Lock Period",
    "staking.estimatedDaily": "Estimated Daily",
    "staking.yield": "yield",
    "staking.stakeNow": "Stake Now",
    "staking.dailyYield": "Daily Yield Performance",
    "staking.rewardPoolYield": "7-Day Reward Pool Yield History",
    "staking.howStakingWorks": "How Staking Rewards Work",
    "staking.sustainableRewards": "Sustainable Rewards",
    "staking.sustainableDesc":
      "Rewards come from platform transaction fees, not token inflation. This ensures long-term sustainability.",
    "staking.feeDistribution": "Fee Distribution",
    "staking.feeDistributionDesc":
      "70% of platform fees are distributed to stakers, 20% for operations, 10% for development.",
    "staking.lockPeriodBenefits": "Benefits of Lock Period",
    "staking.lockPeriodBenefitsDesc":
      "Longer staking periods receive higher reward multipliers. Minimum 30 days, optimal at 90 days.",

    // Redemption Page
    "redemption.title": "Gold Redemption",
    "redemption.subtitle": "Exchange your G-Tokens for physical gold",
    "redemption.redeemTokens": "Exchange G-Tokens",
    "redemption.burnTokens": "Exchange tokens for physical gold",
    "redemption.requiresKYC":
      "Redemption requires completed KYC verification and a physical visit to the selected outlet.",
    "redemption.tokensToRedeem": "G-Tokens to Exchange",
    "redemption.goldWeight": "Gold Weight",
    "redemption.estimatedValue": "Estimated Value",
    "redemption.processingFee": "Processing Fee",
    "redemption.pegadaianOutlet": "Pegadaian Outlet",
    "redemption.selectPickupLocation": "Select pickup location",
    "redemption.generateRedemptionCode": "Generate Redemption Code",
    "redemption.redemptionCode": "Redemption Code",
    "redemption.howItWorks": "How It Works",
    "redemption.codeGenerated": "Code Generated",
    "redemption.visitOutlet": "Visit Selected Outlet",
    "redemption.bringValidID": "Bring valid ID and show this code",
    "redemption.verificationProcess": "Verification Process",
    "redemption.staffWillVerify": "Staff will verify your identity and code",
    "redemption.receiveGold": "Receive Gold",
    "redemption.getPhysicalGold": "Receive your physical gold bars/coins",
    "redemption.codeValidFor": "Code valid for 30 days. Processing time: 1-2 business days.",
    "redemption.redemptionDetails": "Redemption Details",
    "redemption.importantInformation": "Important information about your redemption",
    "redemption.exchangeProcess": "Exchange Process",
    "redemption.tokensAreBurned": "G-Tokens are withdrawn from your account",
    "redemption.goldReleased": "Physical gold is released from the vault",
    "redemption.availableForPickup": "Available for pickup at the selected outlet",
    "redemption.formVerified": "Form verified with government ID",
    "redemption.quickFacts": "Quick Facts",
    "redemption.minimumAmount": "Minimum Amount",
    "redemption.maximumAmount": "Maximum Amount",
    "redemption.processingTime": "Processing Time",
    "redemption.unlimited": "Unlimited",
    "redemption.oneToTwo": "1-2 days",
    "redemption.grams": "grams",
    "redemption.available": "Available",
    "redemption.requirements": "Requirements",

    // Swap Page
    "swap.title": "Token Exchange",
    "swap.subtitle": "Exchange currency for tokenized gold",
    "swap.realTimeGoldPrice": "Real-time Gold Price",
    "swap.tokenSwap": "Token Exchange",
    "swap.tokenSwapDesc": "Exchange between IDRX/USDC and G-TOKEN",
    "swap.from": "From",
    "swap.to": "To",
    "swap.balance": "Balance",
    "swap.exchangeRate": "Exchange Rate",
    "swap.platformFee": "Transaction Fee",
    "swap.feeAmount": "Fee Amount",
    "swap.previewSwap": "Preview Exchange",
    "swap.transactionPreview": "Transaction Preview",
    "swap.transactionPreviewDesc": "Review your exchange details before confirmation",
    "swap.youPay": "You Pay",
    "swap.youReceive": "You Receive",
    "swap.cancel": "Cancel",
    "swap.confirmSwap": "Confirm Exchange",
    "swap.update": "Update",
    "swap.fallbackMode": "Fallback Mode Active",
    "swap.calculationTest": "Live Calculation Test",
    "swap.demonstrating": "Demonstrating fallback price calculation in real-time",
    "swap.inputAmount": "Input Amount",
    "swap.goldPrice": "Gold Price",
    "swap.afterFee": "After Fee",
    "swap.tokensReceived": "Tokens Received",
    "swap.goldEquivalent": "Gold Equivalent",
    "swap.calculationFormula": "Calculation Formula",
    "swap.demo": "Demo",
    "swap.loadingData": "Loading exchange data...",
    "swap.connectionError": "Connection Error",
    "swap.failedLoadData": "Failed to load contract data. Using default values.",
    "swap.tokenApproval": "Token Approval",
    "swap.approveIDRTSpending": "Approve IDRT spending",
    "swap.executeSwap": "Execute Exchange",
    "swap.convertTokens": "Exchange tokens using smart contract",
    "swap.updateBalances": "Update Balances",
    "swap.refreshWallet": "Refresh wallet balance",
    "swap.started": "Transaction Started",
    "swap.swapping": "Exchanging",
    "swap.step1TokenApproval": "Step 1: Token Approval",
    "swap.approvingIDRT": "Approving IDRT for exchange contract...",
    "swap.approvalConfirmed": "Approval Confirmed",
    "swap.idrtApproved": "IDRT spending approval successful",
    "swap.step2ExecutingSwap": "Step 2: Executing Exchange",
    "swap.convertingIDRT": "Exchanging IDRT to G-TOKEN...",
    "swap.completed": "Exchange Completed",
    "swap.receivedTokens": "Received G-TOKEN",
    "swap.goldEq": "grams of gold",
    "swap.summary": "Transaction Summary",
    "swap.fee": "Fee",
    "swap.rate": "Rate",
    "swap.live": "LIVE",
    "swap.portfolioUpdated": "Portfolio Updated",
    "swap.balancesUpdated": "Your token balances have been updated successfully",
    "swap.swapFailed": "Exchange Failed",
    "swap.failedCheck": "Transaction failed. Please check your balance and try again.",
    "swap.demo1M": "Demo: 1M IDRT",
  },
  id: {
    // Navigation
    "nav.home": "Beranda",
    "nav.vault": "Brankas",
    "nav.swap": "Tukar",
    "nav.staking": "Staking",
    "nav.redemption": "Penebusan",
    "nav.portfolio": "Portofolio",
    "nav.connectWallet": "Hubungkan Dompet",
    "nav.refresh": "Segarkan",
    "nav.refreshing": "Menyegarkan...",

    // Home Page
    "home.title": "Investasi Emas Tertoken",
    "home.subtitle":
      "Miliki emas fisik melalui teknologi blockchain. Setiap G-Token didukung oleh emas asli yang disimpan di brankas aman.",
    "home.currentGoldPrice": "Harga Emas Saat Ini",
    "home.buyGoldToken": "Beli Token Emas",
    "home.connectWallet": "Hubungkan Dompet",
    "home.physicalGoldBacked": "100% Didukung Emas Fisik",
    "home.physicalGoldBackedDesc":
      "Setiap G-Token didukung oleh emas fisik yang disimpan di brankas bersertifikat dengan audit rutin dan bukti cadangan.",
    "home.stakingRewards": "Hadiah Staking",
    "home.stakingRewardsDesc":
      "Dapatkan hadiah dengan melakukan staking G-Token Anda. Hadiah berasal dari biaya transaksi platform, memastikan keberlanjutan.",
    "home.redeemAnytime": "Tebus Kapan Saja",
    "home.redeemAnytimeDesc":
      "Konversi G-Token Anda kembali ke emas fisik di outlet Pegadaian mana pun. Sederhana, aman, dan transparan.",
    "home.liveVaultStats": "Statistik Brankas Langsung",
    "home.liveVaultStatsDesc": "Data real-time dari cadangan emas aman kami",
    "home.totalGoldInVault": "Total Emas di Brankas",
    "home.totalGTokens": "Total G-Token",
    "home.totalValue": "Total Nilai",
    "home.latestAudit": "Audit Terakhir",
    "home.verified": "Terverifikasi ✓",
    "home.currentMarketValue": "Nilai pasar saat ini",
    "home.comparisonTitle": "Perbandingan Harga: Emas Fisik vs G-TOKEN",
    "home.comparisonSubtitle": "Lihat perbedaan harga emas fisik dengan G-TOKEN",
    "home.physicalGoldPrice": "Harga Emas Fisik Terkini",
    "home.gTokenFeatures": "Fitur Premium G-TOKEN",
    "home.premiumPricingRationale":
      "G-TOKEN memberikan nilai tambah signifikan melalui kemudahan trading digital, likuiditas 24/7, eliminasi biaya penyimpanan, dan keamanan blockchain.",
    "home.buyPrice": "Harga Beli G-TOKEN",
    "home.sellPrice": "Harga Jual G-TOKEN",
    "home.percentageFromGold": "+85% dari emas",
    "home.percentageFromGold70": "+70% dari emas",
    "home.tradingHours": "Jam Perdagangan",
    "home.alwaysAvailable": "Selalu Tersedia",

    // Vault Page
    "vault.title": "Brankas Emas",
    "vault.subtitle": "Cadangan transparan dan jejak audit",
    "vault.currentHoldings": "Kepemilikan Saat Ini",
    "vault.goldReserveTitle": "Cadangan Emas Brankas",
    "vault.liveGoldReserves": "Cadangan emas real-time yang mendukung G-Token",
    "vault.physicalGold": "Emas Fisik",
    "vault.usdValue": "Nilai USD",
    "vault.idxValue": "Nilai IDRX",
    "vault.vaultLocation": "Lokasi Brankas",
    "vault.insuranceCoverage": "Perlindungan Asuransi",
    "vault.proofOfReserve": "Bukti Cadangan",
    "vault.cryptographicProof": "Bukti kriptografis cadangan emas",
    "vault.reserveRatio": "Rasio Cadangan 100%",
    "vault.allTokensFullyBacked": "Semua token didukung sepenuhnya",
    "vault.tokensIssued": "G-Token yang Diterbitkan",
    "vault.goldReserved": "Emas yang Dicadangkan",
    "vault.perfectMatch": "Kecocokan Sempurna 1:1",
    "vault.viewFullReport": "Lihat Laporan Lengkap",
    "vault.auditTrail": "Jejak Audit Timeline",
    "vault.auditHistory": "Riwayat lengkap audit brankas dan verifikasi",
    "vault.monthlyAudit": "Audit Bulanan",
    "vault.verified": "Terverifikasi",
    "vault.quarterlyReview": "Tinjauan Triwulanan",
    "vault.auditedBy": "Diaudit oleh",

    // Staking Page
    "staking.title": "Dashboard Staking",
    "staking.subtitle": "Dapatkan hadiah dengan melakukan staking G-Token Anda",
    "staking.yourStakingPosition": "Posisi Staking Anda",
    "staking.currentStatus": "Status staking dan hadiah saat ini",
    "staking.gTokensStaked": "G-Token yang Di-Stake",
    "staking.estimatedRewards": "Hadiah yang Diperkirakan",
    "staking.durationStaked": "Durasi Di-Stake",
    "staking.stakingProgress": "Kemajuan Staking",
    "staking.days": "hari",
    "staking.minimumStaking": "Periode staking minimum: 30 hari • Hadiah optimal pada 90 hari",
    "staking.stakeMore": "Staking Lebih Banyak",
    "staking.claimRewards": "Klaim Hadiah",
    "staking.unstake": "Batalkan Stake",
    "staking.stakeGTokens": "Staking G-Token",
    "staking.lockTokens": "Kunci token untuk mendapatkan hadiah",
    "staking.amountToStake": "Jumlah untuk Di-Stake",
    "staking.available": "Tersedia",
    "staking.currentAPY": "APY Saat Ini",
    "staking.lockPeriod": "Periode Penguncian",
    "staking.estimatedDaily": "Perkiraan Harian",
    "staking.yield": "hasil",
    "staking.stakeNow": "Staking Sekarang",
    "staking.dailyYield": "Performa Yield Harian",
    "staking.rewardPoolYield": "Riwayat yield pool hadiah 7 hari",
    "staking.howStakingWorks": "Bagaimana Staking Hadiah Bekerja",
    "staking.sustainableRewards": "Hadiah Berkelanjutan",
    "staking.sustainableDesc":
      "Hadiah berasal dari biaya transaksi platform, bukan inflasi token. Ini memastikan keberlanjutan jangka panjang.",
    "staking.feeDistribution": "Distribusi Biaya",
    "staking.feeDistributionDesc":
      "70% biaya platform didistribusikan kepada staker, 20% untuk operasi, 10% untuk pengembangan.",
    "staking.lockPeriodBenefits": "Manfaat Periode Penguncian",
    "staking.lockPeriodBenefitsDesc":
      "Periode staking yang lebih lama menerima pengganda hadiah yang lebih tinggi. 30 hari minimum, optimal pada 90 hari.",

    // Redemption Page
    "redemption.title": "Penebusan Emas",
    "redemption.subtitle": "Tukarkan G-Token Anda ke emas fisik",
    "redemption.redeemTokens": "Tukarkan G-Token",
    "redemption.burnTokens": "Tukarkan token untuk menerima emas fisik",
    "redemption.requiresKYC":
      "Penebusan memerlukan verifikasi KYC yang sudah selesai dan kunjungan fisik ke outlet yang dipilih.",
    "redemption.tokensToRedeem": "G-Token untuk Ditukarkan",
    "redemption.goldWeight": "Berat Emas",
    "redemption.estimatedValue": "Nilai Perkiraan",
    "redemption.processingFee": "Biaya Pemrosesan",
    "redemption.pegadaianOutlet": "Outlet Pegadaian",
    "redemption.selectPickupLocation": "Pilih lokasi pengambilan",
    "redemption.generateRedemptionCode": "Buat Kode Penebusan",
    "redemption.redemptionCode": "Kode Penebusan",
    "redemption.howItWorks": "Cara Kerjanya",
    "redemption.codeGenerated": "Kode Dibuat",
    "redemption.visitOutlet": "Kunjungi Outlet yang Dipilih",
    "redemption.bringValidID": "Bawa ID yang berlaku dan tunjukkan kode ini",
    "redemption.verificationProcess": "Proses Verifikasi",
    "redemption.staffWillVerify": "Staf akan memverifikasi identitas dan kode Anda",
    "redemption.receiveGold": "Terima Emas",
    "redemption.getPhysicalGold": "Dapatkan batang/koin emas fisik Anda",
    "redemption.codeValidFor": "Kode berlaku selama 30 hari. Waktu pemrosesan: 1-2 hari kerja.",
    "redemption.redemptionDetails": "Detail Penebusan",
    "redemption.importantInformation": "Informasi penting tentang penebusan Anda",
    "redemption.exchangeProcess": "Proses Pertukaran",
    "redemption.tokensAreBurned": "G-Token ditarik dari akun Anda",
    "redemption.goldReleased": "Emas fisik dikeluarkan dari brankas",
    "redemption.availableForPickup": "Tersedia untuk diambil di outlet yang dipilih",
    "redemption.formVerified": "Formulir diverifikasi dengan ID pemerintah",
    "redemption.quickFacts": "Fakta Cepat",
    "redemption.minimumAmount": "Jumlah Minimum",
    "redemption.maximumAmount": "Jumlah Maksimum",
    "redemption.processingTime": "Waktu Pemrosesan",
    "redemption.unlimited": "Tanpa Batas",
    "redemption.oneToTwo": "1-2 hari",
    "redemption.grams": "gram",
    "redemption.available": "Tersedia",
    "redemption.requirements": "Persyaratan",

    // Swap Page
    "swap.title": "Pertukaran Token",
    "swap.subtitle": "Tukar rupiah dengan token berlapis emas",
    "swap.realTimeGoldPrice": "Harga Emas Real-time",
    "swap.tokenSwap": "Pertukaran Token",
    "swap.tokenSwapDesc": "Pertukaran antara IDRX/USDC dan G-TOKEN",
    "swap.from": "Dari",
    "swap.to": "Ke",
    "swap.balance": "Saldo",
    "swap.exchangeRate": "Kurs",
    "swap.platformFee": "Biaya Transaksi",
    "swap.feeAmount": "Jumlah Biaya",
    "swap.previewSwap": "Pratinjau Pertukaran",
    "swap.transactionPreview": "Pratinjau Transaksi",
    "swap.transactionPreviewDesc": "Tinjau detail pertukaran Anda sebelum konfirmasi",
    "swap.youPay": "Anda Bayar",
    "swap.youReceive": "Anda Terima",
    "swap.cancel": "Batal",
    "swap.confirmSwap": "Konfirmasi Pertukaran",
    "swap.update": "Pembaruan",
    "swap.fallbackMode": "Mode Cadangan Aktif",
    "swap.calculationTest": "Pengujian Perhitungan Langsung",
    "swap.demonstrating": "Mendemonstrasikan perhitungan harga cadangan secara real-time",
    "swap.inputAmount": "Jumlah Masukan",
    "swap.goldPrice": "Harga Emas",
    "swap.afterFee": "Setelah Biaya",
    "swap.tokensReceived": "Token yang Diterima",
    "swap.goldEquivalent": "Setara Emas",
    "swap.calculationFormula": "Formula Perhitungan",
    "swap.demo": "Demo",
    "swap.loadingData": "Memuat data pertukaran...",
    "swap.connectionError": "Kesalahan Koneksi",
    "swap.failedLoadData": "Gagal memuat data kontrak. Menggunakan nilai default.",
    "swap.tokenApproval": "Persetujuan Token",
    "swap.approveIDRTSpending": "Setujui pengeluaran IDRT",
    "swap.executeSwap": "Jalankan Pertukaran",
    "swap.convertTokens": "Tukarkan token menggunakan kontrak pintar",
    "swap.updateBalances": "Perbarui Saldo",
    "swap.refreshWallet": "Segarkan saldo dompet",
    "swap.started": "Transaksi Dimulai",
    "swap.swapping": "Menukar",
    "swap.step1TokenApproval": "Langkah 1: Persetujuan Token",
    "swap.approvingIDRT": "Menyetujui IDRT untuk kontrak pertukaran...",
    "swap.approvalConfirmed": "Persetujuan Dikonfirmasi",
    "swap.idrtApproved": "Persetujuan pengeluaran IDRT berhasil",
    "swap.step2ExecutingSwap": "Langkah 2: Menjalankan Pertukaran",
    "swap.convertingIDRT": "Menukar IDRT ke G-TOKEN...",
    "swap.completed": "Pertukaran Selesai",
    "swap.receivedTokens": "Menerima G-TOKEN",
    "swap.goldEq": "gram emas",
    "swap.summary": "Ringkasan Transaksi",
    "swap.fee": "Biaya",
    "swap.rate": "Kurs",
    "swap.live": "LANGSUNG",
    "swap.portfolioUpdated": "Portofolio Diperbarui",
    "swap.balancesUpdated": "Saldo token Anda telah diperbarui dengan sukses",
    "swap.swapFailed": "Pertukaran Gagal",
    "swap.failedCheck": "Transaksi gagal. Silakan periksa saldo Anda dan coba lagi.",
    "swap.demo1M": "Demo: 1M IDRT",

    // Wallet
    "wallet.connecting": "Menghubungkan...",
    "wallet.walletDetails": "Detail Dompet",
    "wallet.address": "Alamat",
    "wallet.balance": "Saldo",
    "wallet.network": "Jaringan",
    "wallet.switchNetwork": "Ganti Jaringan",
    "wallet.selectNetwork": "Pilih Jaringan",
    "wallet.selectNetworkDesc": "Pilih jaringan yang ingin dihubungkan",
    "wallet.reinitializeWallet": "Inisialisasi Ulang Dompet",
    "wallet.viewOnExplorer": "Lihat di Explorer",
    "wallet.disconnect": "Putuskan",
    "wallet.connected": "Dompet Terhubung",
    "wallet.connectedDesc": "Berhasil terhubung ke",
    "wallet.disconnected": "Dompet Terputus",
    "wallet.disconnectedDesc": "Dompet Anda telah terputus",
    "wallet.networkSwitched": "Jaringan Diganti",
    "wallet.networkSwitchedDesc": "Beralih ke",
    "wallet.refreshed": "Dompet Disegarkan",
    "wallet.refreshedDesc": "Saldo dan status koneksi diperbarui",
    "wallet.connectionFailed": "Koneksi Gagal",
    "wallet.connectionFailedDesc": "Gagal menghubungkan dompet. Silakan coba lagi.",
    "wallet.addressCopied": "Alamat Disalin",
    "wallet.addressCopiedDesc": "Alamat dompet disalin ke clipboard",

    // Month Names for Audit Trail Dates
    "month.des": "Des",
    "month.nov": "Nov",
    "month.okt": "Okt",
    "month.sep": "Sep",
    "month.aug": "Ags",
    "month.jul": "Jul",

    // Pegadaian Outlet Translations
    "outlet.jakarta.pusat": "Pegadaian Jakarta Pusat",
    "outlet.jakarta.pusat.address": "Jl. Medan Merdeka Barat No. 1",
    "outlet.thamrin": "Pegadaian Thamrin",
    "outlet.thamrin.address": "Jl. MH Thamrin No. 15",
    "outlet.sudirman": "Pegadaian Sudirman",
    "outlet.sudirman.address": "Jl. Jend. Sudirman Kav. 25",
    "outlet.surabaya": "Pegadaian Surabaya Pusat",
    "outlet.surabaya.address": "Jl. Pemuda No. 12",
    "outlet.bandung": "Pegadaian Bandung Asia Afrika",
    "outlet.bandung.address": "Jl. Asia Afrika No. 65",
  },
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>("en")

  const t = (key: string): string => {
    return translations[language][key as keyof (typeof translations)[typeof language]] || key
  }

  return <LanguageContext.Provider value={{ language, setLanguage, t }}>{children}</LanguageContext.Provider>
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider")
  }
  return context
}
