import Link from "next/link"
import { ArrowRight, BarChart3, Building2, CheckCircle2, Code2, Headphones, Layers3, ShieldCheck } from "lucide-react"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Card, CardContent } from "@/components/ui/card"

const props = [{ icon: ShieldCheck, title: "Regulatory-ready", text: "Compliance rails and identity controls designed for professional capital." }, { icon: BarChart3, title: "Deep liquidity", text: "Efficient access to gold-backed exposure with transparent pricing." }, { icon: Code2, title: "API access", text: "Build treasury, trading, and reporting workflows on reliable rails." }, { icon: Headphones, title: "Dedicated support", text: "A specialist team for onboarding, settlement, and ongoing operations." }]

export default function InstitutionalPage() { return <main className="min-h-screen px-4 py-12 text-soft-white"><div className="mx-auto max-w-7xl"><section className="relative overflow-hidden rounded-3xl border border-gold/25 bg-gradient-to-br from-gold/20 via-navy-800/80 to-navy-900 p-8 md:p-16"><Badge className="border-gold/30 bg-gold/10 text-gold">AuriX Institutional</Badge><h1 className="mt-6 max-w-4xl text-5xl font-bold tracking-tight md:text-7xl">Emas untuk portofolio institusional Anda.</h1><p className="mt-6 max-w-2xl text-lg leading-relaxed text-soft-white/65">Akses infrastruktur gold-backed yang transparan untuk treasury, asset managers, fintech, dan family offices.</p><div className="mt-8 flex flex-wrap gap-3"><Button className="bg-gold text-navy-900 hover:bg-gold-300">Request a demo <ArrowRight className="ml-2 size-4" /></Button><Button variant="outline" className="border-gold/30 text-gold hover:bg-gold/10">Download fact sheet</Button></div></section><section className="mt-10 grid gap-4 md:grid-cols-2 lg:grid-cols-4">{props.map(({ icon: Icon, title, text }) => <Card key={title} className="border-soft-white/10 bg-navy-800/50"><CardContent className="p-6"><Icon className="size-7 text-gold" /><h2 className="mt-5 font-semibold">{title}</h2><p className="mt-2 text-sm leading-relaxed text-soft-white/60">{text}</p></CardContent></Card>)}</section><section className="mt-10 grid gap-6 lg:grid-cols-2"><Card className="border-gold/20 bg-navy-800/60"><CardContent className="p-8"><Building2 className="size-8 text-gold" /><h2 className="mt-5 text-3xl font-semibold">One platform, multiple operating models.</h2><div className="mt-6 grid gap-4 sm:grid-cols-2">{["Bulk trading", "OTC desk", "Custom redemption", "White-label infrastructure"].map((item) => <div key={item} className="flex items-center gap-2 text-sm text-soft-white/75"><CheckCircle2 className="size-4 text-prosperity" />{item}</div>)}</div></CardContent></Card><Card className="border-prosperity/20 bg-navy-800/60"><CardContent className="p-8"><Layers3 className="size-8 text-prosperity" /><h2 className="mt-5 text-3xl font-semibold">Designed for scale.</h2><p className="mt-3 leading-relaxed text-soft-white/60">From first allocation to daily settlement, your team gets visibility across custody, compliance, liquidity, and redemption.</p><Button asChild variant="ghost" className="mt-6 px-0 text-gold hover:bg-transparent hover:text-gold-300"><Link href="/transparency">Explore our infrastructure <ArrowRight className="ml-2 size-4" /></Link></Button></CardContent></Card></section></div></main> }
